## serialization : process of converting python data types to json format
## deserializatioin : process of converting json to python data types format

In [23]:
import json
L = [1,2,3,4,5]

with open("practice/srinu.json", 'w') as f:
   data = json.dump(L,f)
   print(data)
   print(type(data))

None
<class 'NoneType'>


In [27]:
d={ 'car':'benz',
   'tyres': 4,
   'engines':1
   }
with open("practice/srinu.json", 'w') as f:
   json.dump(d,f, indent=4)


In [3]:
with open("practice/srinu.json", 'r') as f:
   data = json.load(f)
   print(data)
   print(type(data))

{'car': 'benz', 'tyres': 4, 'engines': 1}
<class 'dict'>


# pickling in python

In [4]:
def display_info():
    return("hi srinu kya hua")

In [5]:
d = display_info()

In [6]:
import pickle

with open("practice/srinu.pkl", 'wb') as f:
    pickle.dump(d,f)

In [7]:
with open("practice/srinu.pkl", 'rb') as f:
    p = pickle.load(f)
    print(p)

hi srinu kya hua


f-strings

In [8]:
name = 'srinu'
age= 25

s= f"my name is {name} and age is {age}"
print(s)

my name is srinu and age is 25


In [9]:
s= "my name is {} and age is {}"
print(s.format(name, age))

my name is srinu and age is 25


## lista

In [10]:
'"lists are dynamic and slow and heterogeneous and copy is happening when we add another item into list. on the other hand arrays are of fixed size. list item address are assigned to different id "'

'"lists are dynamic and slow and heterogeneous and copy is happening when we add another item into list. on the other hand arrays are of fixed size. list item address are assigned to different id "'

In [11]:
list('hello')

['h', 'e', 'l', 'l', 'o']

In [12]:
l = [1,2,3,4,5,6]
l.append(6)
print(l)


[1, 2, 3, 4, 5, 6, 6]


In [13]:
l.extend([1,2,3,4,5])
l.insert(2,200)
print(l)

[1, 2, 200, 3, 4, 5, 6, 6, 1, 2, 3, 4, 5]


In [14]:
"delete, remove, pop, clear = remove removes certain elements and pop removes last item and clear removes entire all elements"

""#del l[1:3]
   #l.remove(4)""

''

##zip function

In [15]:
l1= [1,2,3,4,5]
l2 = [6,7,8,9,10,11,12,13,14]
l3 = [15,16,17,18,19,20,21,22,23]

print(list(zip(l1,l2,l3)))

[(1, 6, 15), (2, 7, 16), (3, 8, 17), (4, 9, 18), (5, 10, 19)]


##tuple

In [16]:
s=()
type(s)

tuple

In [17]:
s= tuple('hello')

In [18]:
s

('h', 'e', 'l', 'l', 'o')

In [19]:
s= (1,2,3,4,5)
print(type(s))
t=list(s)
t.append(30)
h=tuple(t)
print(h)

<class 'tuple'>
(1, 2, 3, 4, 5, 30)


In [20]:
#operations on tuple

In [21]:
P =(1,2,3,3,4,5)
Q= (1,2,3,4,5)
P+Q
P*3
6 not in p


TypeError: 'in <string>' requires string as left operand, not int

In [25]:
## tuples unpacking

a,b,*others= (1,2,3,4,45.67,78)
print(a,b)

1 2


In [27]:
## tuple comprehension

s= tuple((i for i in range(11)))
print(s)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [1]:
## sets

##set is unoredered, mutable, no duplicates and elements inside the set are immutable.
s = set()
s = {1,2,3,4,5}
print(len(s))
print(sum(s))
print(sorted(s, reverse = True))

5
15
[5, 4, 3, 2, 1]


In [4]:
s1 = {1,2,3,4}
s2 = {5,6,7,8}
s1.union(s2)
s1.update(s2)
print(s1)
print(s2)

{1, 2, 3, 4, 5, 6, 7, 8}
{8, 5, 6, 7}


In [5]:
s1 = {1,2,3,5}
s2 = {5,6,9,8}
s1.intersection(s2)
s1.intersection_update(s2)
print(s1)
print(s2)
s1.symmetric_difference(s2)
s1.symmetric_difference_update(s2)
print(s1)
print(s2)

{5}
{8, 9, 5, 6}
{8, 9, 6}
{8, 9, 5, 6}


In [9]:
s3 = {1,5,6,7,8,4,9}
s4 = {9,7,6,5,4}

print(s3.isdisjoint(s4))
print(s4.issubset(s3))
print(s3.issuperset(s4))

False
True
True


In [1]:
##Numpy

In [2]:
import numpy as np

In [11]:
a = np.array([1,2,3])
a
print(a.shape)
print(len(a))
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.astype(float))
print(a.tolist())

(3,)
3
1
3
int32
[1. 2. 3.]
[1, 2, 3]


In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,3,4),dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
##create ana array of evenly specified values with step size
print(np.arange(10,26,5))
##create an array of evenly specified values with specified number of samples
print(np.linspace(0,2,9))

[10 15 20 25]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [20]:
a = np.logspace(1,3,5)
print(a)
b= np.log10(a)
print(b)

[  10.           31.6227766   100.          316.22776602 1000.        ]
[1.  1.5 2.  2.5 3. ]


In [22]:
##create an constant array with shape and constant

np.full((2,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [27]:
## create an identity matrix 
np.eye(3)
## create an array of values between o and 1 that follow a uniform distribution
np.random.random((3,2))
##create an array of values that follow a standard normal distribution
np.random.randn(2,3)
## create an array of values that follows a standard normal distribution with mean = 1 and std =2
np.random.normal(loc=1, scale=2, size=(3,2))

array([[ 4.29394122,  1.80348778],
       [ 2.30072836,  2.56564814],
       [-1.25079299,  1.7487847 ]])

In [33]:
a1= np.array([[1,2,3], [4,5,6]])
a2 = np.array([6,7,9,8])
np.sort(a2)

array([6, 7, 8, 9])

In [43]:
b2 = a2.copy()
b2
a3 = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(a3)
print('\n')
print(a3.flatten())
print(a3.ravel())
print(a3.T)
print(a3.transpose())
print(a3.reshape(3,3))
## adding the elements to the array
np.append(a3, -10)
## inserting the elements into the correct location in array
np.insert(a3, 1, 100)
## deleting the elements from the array
np.delete(a3, 1, axis = 0)
np.delete(a3,1, axis = 1)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


[1 2 3 2 3 4 3 4 5]
[1 2 3 2 3 4 3 4 5]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


array([[1, 3],
       [2, 4],
       [3, 5]])

In [52]:
b1 = ([[1,2,3],[3,4,5]])
b2 = ([[6,7,8],[2,3,4]])
np.concatenate((b1,b2), axis = 0)
b3 = np.concatenate((b1,b2),axis= 1)
np.vstack((b1,b2))
np.r_[b1,b2]
np.hstack((b1,b2))
np.c_[b1,b2]
np.vsplit(b3, 2)

[array([[1, 2, 3, 6, 7, 8]]), array([[3, 4, 5, 2, 3, 4]])]

In [56]:
c1 = np.arange(16).reshape(4,4)
np.hsplit(c1,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
x= np.arange(10)
x.shape = (2,5)
x[1, 3] = 100
## return multiple elements at indices
print(x[: ,2])
print(x<=5)

[2 7]
[[ True  True  True  True  True]
 [ True False False False False]]


In [71]:
## mask an array
y = np.array([2,4,6,8,10])
y<=3
y[y<=3]
## scalar math operations
z = np.arange(6).reshape(2,3)
print(z)
print(np.add(z,1))
print(np.subtract(z,2))
print(np.divide(z,3))


[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[-2 -1  0]
 [ 1  2  3]]
[[0.         0.33333333 0.66666667]
 [1.         1.33333333 1.66666667]]


In [74]:
## vector math
q = np.arange(6).reshape(2,3)
t = np.full((2,3), 2)
print(q)
print(t)
np.add(q,t)

[[0 1 2]
 [3 4 5]]
[[2 2 2]
 [2 2 2]]


array([[2, 3, 4],
       [5, 6, 7]])

In [1]:
df.head()
df.loc['']
df.shape
df.loc[index,columns]
df.describe()
df['val'].max()
df.max()
df.loc[[list]]
df.loc[[df['valure']==319]]
df['vsl'].mode()
df['val'].value_counts().head()
df.loc[df['val']==276].sort_values(by='values',ascending= True)
df.query('ratio'==10).sort_values(by='values').max()
df.loc['df['ratio'==10',value].max()
(df['type 1 '==1])! (df['type2'==2])
df.query('type1'==10 && 
         'type'==20).shape

SyntaxError: invalid syntax. Perhaps you forgot a comma? (983617210.py, line 14)

In [2]:
import numpy as np

In [3]:
array_1 = np.arange(100000)

In [4]:
np.arange(4,10,2)

array([4, 6, 8])

In [5]:
np.ones([2,3,4,5])

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [8]:
arr_int = np.array([1,2,3,4,5])
print(arr_int.dtype)

print(arr_int.itemsize)

int32
4


In [9]:
arr_sum = np.arange(1000)
a = np.sum(arr_sum)
print(a)

499500


In [10]:
b = np.full((2,2),5)
print(b)


[[5 5]
 [5 5]]


In [12]:
c = np.eye(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
print(c*4)

[[4. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 4.]]


In [14]:
arr = np.arange(1000)
print(arr[::2])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 488 490 49

In [15]:
df = np.array([[1,2,3],
         [4,5,6],
         [6,7,8]])

In [16]:
df[df>3]

array([4, 5, 6, 6, 7, 8])

In [19]:
df[(2,2)]

8

In [20]:
arr_3d =  np.array([[[1,2,3],
                     [2,3,4],
                     [5,6,7]],
                     
                     [[7,8,9],
                      [4,5,6],
                      [1,7,8]]])

In [22]:
arr_3d.shape
arr_4d = np.swapaxes(arr_3d, 0,1)
print(arr_4d)

[[[1 2 3]
  [7 8 9]]

 [[2 3 4]
  [4 5 6]]

 [[5 6 7]
  [1 7 8]]]


In [28]:
d = np.random.randint( 0,10, size= 5)
f =np.random.normal(0,10 , size=6)
print(f)

[12.89441602 -8.98325004 21.77883801 12.68439148 -9.91217782  9.79530051]


In [29]:
d.ravel()

array([1, 7, 5, 8, 2])

ravel and flatten are same but flatten makes a copy of the original array

In [31]:
c = np.array([[[[1,2,3]]]])
sq = c.squeeze()

In [35]:
expanded = np.expand_dims(sq, axis= 1)
print(expanded)

[[1]
 [2]
 [3]]


In [39]:
x = np.arange(9)
d = np.split(x, 3)
print(d)
f = np.array_split(x,4)
print(f)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [40]:
a = np.array([[1,2,3],
              [2,3,4]])

In [45]:
np.hsplit(a,3)

[array([[1],
        [2]]),
 array([[2],
        [3]]),
 array([[3],
        [4]])]